# Generated by Django 4.1.1 on 2022-09-05 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('actividad_economica', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=10)),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgrupo16.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos_Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ingresos', models.FloatField()),
                ('gastos', models.FloatField()),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgrupo16.empresa')),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgrupo16.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgrupo16.usuario'),
        ),
    ]
