# Generated by Django 4.1.1 on 2022-09-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgrupo16', '0002_rename_identificacion_empresa_nombre_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='cargo',
            new_name='rol',
        ),
    ]
