# Generated by Django 4.1.1 on 2022-09-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgrupo16', '0005_remove_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(max_length=50),
        ),
    ]
