# Generated by Django 4.1.1 on 2022-09-08 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgrupo16', '0006_alter_usuario_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgrupo16.empleado'),
        ),
    ]
