# Generated by Django 4.1.1 on 2022-09-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgrupo16', '0009_alter_usuario_identificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='identificacion',
            new_name='rol',
        ),
    ]
