# Generated by Django 4.1.1 on 2022-09-20 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgrupo16', '0013_usuario_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='rol',
            new_name='cargo',
        ),
    ]
